export const genres = [
  { genre: 'Reggeaton', value: 0 },
  { genre: 'Latino', value: 0 },
  { genre: 'Brasilero', value: 0 },
  { genre: 'Cuarteto Retro', value: 0 },
  { genre: 'Cuarteto Actual', value: 0 },
  { genre: 'Cumbias Retro', value: 0 },
  { genre: 'Cumbias Actuales', value: 0 },
  { genre: 'Cumbia Canchera', value: 0 },
  { genre: 'Bachata', value: 0 },
  { genre: 'Pop Latino', value: 0 },
  { genre: 'Pop Internacional', value: 0 },
  { genre: 'Reggae', value: 0 },
  { genre: 'Electro Nueva', value: 0 },
  { genre: 'Electro retro 90', value: 0 },
  { genre: "POP 60'", value: 0 },
  { genre: "POP 80'", value: 0 },
  { genre: "POP 90'", value: 0 },
  { genre: 'Disco', value: 0 },
  { genre: 'Rock & Roll', value: 0 },
  { genre: 'Nacionales Retro', value: 0 },
  { genre: 'Nacionales Actuales', value: 0 },
  { genre: 'Lentos 80/90', value: 0 },
  { genre: 'Lentos actuales', value: 0 },
  { genre: 'Trap', value: 0 }
];
